<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\..\..\..\Desktop\giriş_yap_hero.webp" Link="wwwroot\images\giriş_yap_hero.webp" />
    <None Include="..\..\..\..\..\Desktop\icon.webp" Link="wwwroot\images\icon.webp" />
  </ItemGroup>

</Project>
